### PR TITLE
fixed CollectionShouldOnlyHaveUniqueItemsByComparer gives invalid code

### LINKED ISSUE #63: CollectionShouldOnlyHaveUniqueItemsByComparer gives invalid code
### Description

`CollectionShouldOnlyHaveUniqueItemsByComparer` is triggered by this code
```csharp
var list = new[] { 1, 2, 3 };

list.Select(e => e.ToString())
    .Where(e => e != "")
    .Should()
    .OnlyHaveUniqueItems();
```

Which turns it into this invalid code, as the `Where` now tries to compare an `int` to a `string`.
```csharp
var list = new[] { 1, 2, 3 };

list.Where(e => e != "")
    .Should()
    .OnlyHaveUniqueItems(e => e.ToString());
```

### Expected behavior:

The analyzer should not be triggered.

### Actual behavior:

The analyzer is triggered.

### Versions

Fluent Assertions Analyzers 0.11.2
.NET Framework 4.6.1

### PR DESCRIPTION
**Pull request by Meir017**
closes #63

### CODE REVIEW

**Comment by Meir017** [comment]
@jnyrup with this fix the `CollectionShouldNotBeNullOrEmptyAnalyzer` will not report statements that have a method call between the `NotBeNull` & `NotBeEmpty`

```cs
var actual = new[] { "text1", "text2" };
actual
  .Should().NotBeNull()
  .And.HaveCount(2)
  .And.NotBeEmpty();
```

**Comment by jnyrup** [comment]
I guess one can always write arbitrarily obfuscated code that will hinder an analyzer in detecting patterns.

E.g. this valid but weird code
```csharp
list.Should().NotBeEmpty().And.Should().NotBeNull();
```

is with 0.11.2 transformed into the uncompilable: 
```csharp
list.Should().NotBeNullOrEmpty().And.NotBeNull;
```

I have previously blindly trusted analyzers as "knowing the truth" and just applied its suggestions to e.g. an entire project, only to later find out that the applied code fixes had semantically changes, that broke the code.
I guess for somebody false positives could be a blocker for their adaption of the analyzer.
Roslynator e.g. chose to remove some analyzers, as their correctness could not be guaranteed and hence to could lead to invalid code.

**Comment by Meir017** [comment]
this case is related to the same issue that the analyzers used to look for the method in sequence but allowed method calls to exists between them, now they have to be one after another

**Comment by jnyrup** [comment]
And just to answer your question: I think it's fine to sacrifice functionality over correctness.

**Pull request merged**
