### PR TITLE
docs: generate documentation

### LINKED ISSUE #274: Checklist of all tips and whether they have analyzers
Instead of tracking https://fluentassertions.com/tips/#improved-assertions piecemeal (e.g. #245) there should be an issue checklist in this repo with a here, with each suggested improvement listed as a task.

### PR DESCRIPTION
**Pull request by Meir017**
resolves #274

example of generated docs:

image

### CODE REVIEW

**Comment by dennisdoomen** [comment]
That's pretty cool. But I wonder how we would integrate it into the website.

**Comment by Meir017** [comment]
@dennisdoomen a comment-line program that parses the source code could be executed as part of the website generation (the `collections.md` file could be generated from multiple tests that compile and pass)

**Comment by dennisdoomen** [comment]
But that would require us to take control of the website generation process that GitHub now takes care off. We have no plans to do that unless somebody else takes the work from our plate.

**Comment by Meir017** [comment]
@dennisdoomen I thought that the docs website is generated using the docfx tool, and then adding a dotnet command to build a different project before building the docs would be simple enough.

If I understand correctly `jekyll` is used to generate the docs site (here https://github.com/fluentassertions/fluentassertions/blob/develop/docs/.travis.yml)

**Comment by dennisdoomen** [comment]
Yeah, it's a Jekyll site, but the deploy process is completely handled by GHA. Unless somebody is willing to change that (I don't have the time), your suggestion is not going to be possible.

**Comment by Meir017** [comment]
FYI @dennisdoomen / @jnyrup I'm now able to generate the failure messages as well https://github.com/fluentassertions/fluentassertions.analyzers/blob/main/docs/MsTestAnalyzer.md#scenario-booleanassertistrue
I think this approach will be more reliable than what we have in https://fluentassertions.com/tips/#assert (already out of sync as the subject is now being printed in the error message
image
for the fluentassertion we should print `"Expected actual to be true, but found False."`)

**Pull request merged**
